package com.wgn.dao;

import com.wgn.bean.Student;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Mar 16 16:15:51 CST 2018
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Mar 16 16:15:51 CST 2018
     */
    int insertSelective(Student record);
}